config/routes.rb
Rails.application.routes.draw do
  # get "todos", to: "todos#index"             #lists all the todos
  # post "todos", to: "todos#create"           #adds a todo to the list
  # get "todos/:id", to: "todos#show"          #shows 1 todo based on para id

  # root :to => "/"

  get "/" => "home#index"

  resources :todos

  resources :users

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :todo_text, presence: :true
  validates :todo_text, length: { minimum: 2 }
  validates :due_date, presence: :true
  belongs_to :user

  def self.overdue
    where("due_date < ?", Date.today).order("due_date")
  end

  def self.due_today
    where("due_date = ?", Date.today)
  end

  def self.due_later
    where("due_date > ?", Date.today).order("due_date")
  end

  def self.completed
    where(completed: true)
  end

  def self.not_completed
    where(completed: false)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: :true
  validates :email, presence: :true
  has_secure_password
  has_many :todos
end

app/models/users.rb
class Users < ActiveRecord::Base
  def to_displayable_string
    "\nID:#{id}, \nFirst Name: #{first_name}, \nLast Name: #{last_name}, \nEmail: #{email} \nPassword: #{password_digest} \n"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user

    current_user_id = session[:current_user_id]
    @current_user = current_user_id ? User.find(current_user_id) : nil
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def create
    user = User.find_by(email: params[:email])

    if user
      # give a welcome message (in /todos) if account is signed-in else give flash error
      if user.authenticate(params[:password])
        greeting = "Good " + if Time.now.hour < 12
          "Morning"
        elsif Time.now.hour > 12 && Time.now.hour < 17
          "Afternoon"
        else
          "Evening"
        end
        flash[:welcome] = "#{greeting}, #{user.first_name.capitalize} #{user.last_name.capitalize} :)"
        session[:current_user_id] = user.id
        redirect_to "/"
      else
        flash[:error] = "Password of '#{user.email}' is incorrect. Please retry."
        redirect_to new_sessions_path
      end
    else
      if params[:email] == ""
        flash[:error] = "Please enter your email-id"
      else
        flash[:error] = "No account with user-email '#{params[:email]}' exists. Please retry."
      end
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    # give sign-out success message in homepage(index)
    flash[:notice] = "You have successfully signed out."
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = current_user.todos
    render "index"
  end

  def create
    todo_text = params[:todo_text].strip.downcase.capitalize
    due_date = params[:due_date]

    todo = Todo.find_by(todo_text: todo_text, due_date: due_date, user_id: current_user.id)

    # check if todo already exists within same user
    if todo
      due = if todo.due_date == Date.today
          "Due today"
        elsif todo.due_date < Date.today
          "Overdue"
        else
          "Due later"
        end
      is_completed = todo.completed ? "completed" : "not completed"
      flash[:error] = "Todo with same due date already exists. (Status: #{due} and #{is_completed}) "
      redirect_to todos_path
      # if todo with same date doesnt already exist, create a new one(if todo_text and due_date are filled)
    else
      new_todo = Todo.new(
        todo_text: todo_text,
        due_date: due_date,
        completed: false,
        user_id: current_user.id,
      )
      if new_todo.save
        redirect_to todos_path
      else
        errors = new_todo.errors.full_messages
        if errors.length > 2
          errors.delete_at(1)
        end
        flash[:error] = errors.join(", ")
        redirect_to todos_path
      end
    end
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = current_user.todos.find(id)
    todo.completed = completed
    todo.save
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = current_user.todos.find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def create
    user = User.find_by(email: params[:email])

    # chack if user already exists in db
    if user
      flash[:error] = "Account already exists with given email."
      redirect_to new_user_path
    else
      new_user = User.new(
        first_name: params[:first_name],
        last_name: params[:last_name],
        email: params[:email],
        password: params[:password],
      )
      # give a success message (in homepage) if account is created else give flash error
      if new_user.save
        greeting = "Good " + if Time.now.hour < 12
          "Morning"
        elsif Time.now.hour > 12 && Time.now.hour < 17
          "Afternoon"
        else
          "Evening"
        end
        flash[:welcome] = "#{greeting}, #{new_user.first_name.capitalize} #{new_user.last_name.capitalize} :)"
        flash[:notice] = "You have successfully created a new account."
        session[:current_user_id] = new_user.id
        redirect_to "/"
      else
        flash[:error] = new_user.errors.full_messages.join(", ")
        redirect_to new_user_path
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1 class="Header-title">Welcome to your Todo Manager!</h1>
<hr>

<ol class="Home-authenticate">
  <% if flash[:notice] %>
    <p class="Flash-log">
      <%= flash[:notice] %>
    </p>
  <% end %>

  <li>If you are a new user, <%= link_to "Sign-Up here", new_user_path %></li>
  <li>If you are an existing user, <%= link_to "Sign-In here", new_sessions_path %></li>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="shortcut icon" href="<%= image_url("title-image.png") %>" type="image/x-icon" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
  <% # Welcome message when user signs in %>
    <% if @current_user %>
      <% if flash[:welcome] %>
        <p class="Flash-welcome">
          <%= flash[:welcome] %>
        </p>
      <% end %>
    <% end %>

    <%= yield %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script language="JavaScript" type="text/javascript">
      $(function() {
        $("a.Show-remaining-todos").click(function(event){
          event.preventDefault();
          $("div.remaining-todos").toggle();
          $("a.Show-remaining-todos").toggle();
          $("a.Hide-remaining-todos").toggle();
        });

        $("a.Hide-remaining-todos").click(function(event){
          event.preventDefault();
          $("div.remaining-todos").toggle();
          $("a.Show-remaining-todos").toggle();
          $("a.Hide-remaining-todos").toggle();
        });
      });
    </script>

  </body>
</html>

app/views/todos/_remaining-todos-section.html.erb
<section class="TodoSection">
  <div class="TodoSectionTitle">
    <%= link_to "Show your done and dusted todos", nil, class: "Show-remaining-todos" %>
    <%= link_to "Hide your done and dusted todos", nil, class: "Hide-remaining-todos" %>
  </div>

  <div class="remaining-todos">
    <% if todos.count == 0 %>
      <p style="font-size:14px">No Overdue todos completed yet!</p>

    <% else %>
      <ul class="remaining-todos-list">
        <% todos.all.each do |todo| %>
          <li class="TodoItem">
            <label class="TodoItem-container">
              <p> <%= todo.todo_text %> </p>
              <p class="TodoItem-dueDate"> <%= todo.due_date.to_s(:short) %> </p>

              <a href="javascript:void(0)" class="TodoItem-delete">
                <%= form_with(url: "/todos/#{todo.id}", method: "delete") do %>
                  <%= image_submit_tag("delete.svg", class: "icon", data: { confirm: "Are you sure you want to permanently delete the todo: '#{todo.todo_text}' from the list?" }) %>
                <% end %>
              </a>

            </label>
          </li>
        <% end %>
      </ul>
    <% end %>

  </div>
</section>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
  <div class="TodoSectionTitle">
    <p class="TodoSectionTitle-text"> <%= section_title %> </p>
    <p class="TodoSectionTitle-remainingCount"> <%= todos.completed.count %> / <%= todos.count %> </p>
  </div>

  <ul>
    <% todos.all.each do |todo| %>
      <li class="TodoItem">
        <label class="TodoItem-container">

          <%= form_with(url: "/todos/#{todo.id}", method: "put") do %>
            <%= check_box_tag "completed",
                              nil,
                              todo.completed ? true : false,
                              class: "TodoItem-checkbox",
                              onclick: "this.form.submit()" %>
          <% end %>

          <p style="text-decoration: <%= todo.completed ? "line-through;" : "" %>"> <%= todo.todo_text %> </p>

          <% if show_due_date %>
            <p class="TodoItem-dueDate"> <%= todo.due_date.to_s(:short) %> </p>
          <% end %>

          <a href="javascript:void(0)" class="TodoItem-delete">
            <%= form_with(url: "/todos/#{todo.id}", method: "delete") do %>
              <%= image_submit_tag("delete.svg", class: "icon", data: { confirm: "Are you sure you want to permanently delete the todo: '#{todo.todo_text}' from the list?" }) %>
            <% end %>
          </a>
        </label>
      </li>
    <% end %>
  </ul>
</section>

app/views/todos/index.html.erb
<article>
  <div class="Title">
    <h1 class="TodoPage-title"><%= @current_user.first_name.capitalize %>'s To-do List</h1>
    <%= button_to "Sign-out", destroy_session_path, method: "delete", class: "Sign-out-button" %>
  </div>

  <%= form_with(url: "/todos", method: "post", class: "AddTodo") do %>
    <%= text_field_tag "todo_text", nil, placeholder: "What's next?", class: "AddTodo-text", autofocus: true %>
    <%= date_field_tag "due_date", nil, class: "AddTodo-date" %>
    <%= submit_tag "Add", class: "AddTodo-button" %>
  <% end %>

  <% if flash[:error] %>
    <p class="Flash-error Flash-error-todo">
      <%= flash[:error] %>
    </p>
  <% end %>

  <% if flash[:notice] %>
    <p class="Flash-log">
      <%= flash[:notice] %>
    </p>
  <% end %>

  <!-- Section for Remaining todos (visible only if link clicked) -->
  <%= render partial: "remaining-todos-section", locals: {
               todos: @todos.overdue.completed,
             } %>
  <!-- End of Remaining todos -->

  <!-- Section for Overdue -->
  <%= render partial: "todo-section", locals: {
               section_title: "Overdue",
               todos: @todos.overdue.not_completed,
               show_due_date: true,
             } %>
  <!-- End of Overdue -->

  <!-- Section for Due today -->
  <%= render partial: "todo-section", locals: {
               section_title: "Due Today",
               todos: @todos.due_today,
               show_due_date: false,
             } %>
  <!-- End of Due today -->

  <!-- Section for Due Later -->
  <%= render partial: "todo-section", locals: {
               section_title: "Due Later",
               todos: @todos.due_later,
               show_due_date: true,
             } %>
  <!-- End of Due Later -->
</article>

app/views/users/new.html.erb
<p class="Header-title">Welcome new user!</p>
<hr>

<section class="NewUsers">
  <% if flash[:error] %>
    <p class="Flash-error">
      <%= flash[:error] %>
    </p>
  <% end %>

  <div class="NewUsers-form">
    <%= form_with url: users_path do |form| %>
      <div class="Form-section">
        <p class="Form-input-label">First Name:</p>
        <%= form.text_field :first_name, class: "Form-input" %>
      </div>
      <div class="Form-section">
        <p class="Form-input-label">Last Name:</p>
        <%= form.text_field :last_name, class: "Form-input" %>
      </div>
      <div class="Form-section">
        <p class="Form-input-label">Email:</p>
        <%= form.email_field :email, class: "Form-input" %>
      </div>
      <div class="Form-section">
        <p class="Form-input-label">Password:</p>
        <%= form.password_field :password, class: "Form-input" %>
      </div>

      <div class="Form-section">
        <%= form.submit "Sign-up!", class: "Form-submit" %>
      </div>
    <% end %>
  </div>
</section>